- name: 创建域、项目、用户、角色
  shell:
    cmd: |
         . /root/admin-openrc
         openstack project create --domain default --description "Service Project" service
         openstack project create --domain default --description "Demo Project" demo
         openstack user create --domain default --project demo --password {{openstack_demo_password}} demo
         openstack role create user
         openstack role add --project demo --user demo user