- name: 计算节点安装nova
  yum:
   name: openstack-nova-compute
   state: present

- name: 计算节点配置nova.conf
  shell:
    cmd: |
         test -f /etc/nova/nova.conf.bak || \cp /etc/nova/nova.conf /etc/nova/nova.conf.bak
         cat > /etc/nova/nova.conf << EOF
         [DEFAULT]
         enabled_apis = osapi_compute,metadata
         transport_url = rabbit://openstack:${ServicePasswd}@${rabbitmq_VIP}
         my_ip = ${Manager_IP}
         use_neutron = true
         firewall_driver = nova.virt.firewall.NoopFirewallDriver
         block_device_allocate_retries = 6000
         block_device_allocate_retries_interval = 10
         
         [api]
         auth_strategy = keystone
         
         [keystone_authtoken]
         auth_url = http://${keystone_endpoint_VIP}:5000/v3
         memcached_servers = ${Memcahed_Server_List}
         auth_type = password
         project_domain_name = Default
         user_domain_name = Default
         project_name = service
         username = nova
         password = ${ServicePasswd}
         
         [vnc]
         enabled = true
         server_listen = 0.0.0.0
         server_proxyclient_address = \$my_ip
         novncproxy_base_url = http://${dashboard_public_VIP}:6080/vnc_auto.html
         
         [glance]
         api_servers = http://${glance_endpoint_VIP}:9292
         
         [oslo_concurrency]
         lock_path = /var/lib/nova/tmp
         
         [placement]
         region_name = RegionOne
         project_domain_name = Default
         project_name = service
         auth_type = password
         user_domain_name = Default
         auth_url = http://${keystone_endpoint_VIP}:5000/v3
         username = placement
         password = ${ServicePasswd}
        
         [libvirt]
         virt_type = qemu
         EOF
         var_cpuinfo=`egrep -c '(vmx|svm)' /proc/cpuinfo`
         openstack-config --set /etc/nova/nova.conf libvirt cpu_mode none
         if [ ${var_cpuinfo} -gt 0 ]; then
             openstack-config --set /etc/nova/nova.conf libvirt virt_type qemu
         else
             openstack-config --set /etc/nova/nova.conf libvirt virt_type qemu
         fi